version: '3'

services:
  server:
    image: server
    networks:
      - connection-network
    ports:
      - "8000:8000"

  client:
     image: client
     networks:
       - connection-network
     environment:
       - SOCKET_SERVER_HOST=server
     depends_on:
       - server

networks:
  connection-network:



